### PR TITLE
Pull request to add OSX tcp keepalive support

### PR DESCRIPTION
**Pull request by quanah**
This commit allows this module to build on OSX systems, and adds keeaplive support for them.

### CODE REVIEW

**Comment by quanah** [comment]
I based the patch off of:

http://patches.gluster.com/patch/3303/

TCP_KEEPIDLE and TCP_KEEPINTVL don't exist in the headers for OSX.  IPPROTO_TCP appears to be the standard that should be used to be cross platform compliant, vs SOL_TCP which is linux specific.

**Comment by nviennot** [comment]
I see
Thank you !

**Comment by honzchen** [comment]
Wrong mapping!

SSO(IPPROTO_TCP, TCP_KEEPALIVE, conf->tcp_keepintvl);
=>
SSO(IPPROTO_TCP, TCP_KEEPALIVE, conf->tcp_keepidle);

**Comment by nviennot** [comment]
Can you point me to the documentation ?

**Comment by honzchen** [comment]
check [tcp man page](http://developer.apple.com/library/mac/#DOCUMENTATION/Darwin/Reference/ManPages/man4/tcp.4.html)

**Pull request merged**
